spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes[0]:
          id : user-profile-service
          uri: http://localhost:8081
          predicates[0]:
            Path= /v1/user/**
      routes[1]:
          id: authentication-service
          uri: http://localhost:8082
          predicates[0]:
            Path= /v1/authenticate/**
      routes[2]:
        id: nutrition-service
        uri: http://localhost:8083
        predicates[0]:
          Path= /v1/nutrition/**
      routes[3]:
        id: wishlist-service
        uri: http://localhost:8084
        predicates[0]:
          Path= /v1/wishlist/**

server:
  port: 9090

