server:
  port: 8085
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Satyajit-Pani/nutritionapp-configuration


#          https://github.com/Satyajit-Pani/nutritionapp-configuration/tree/main
#          clone-on-start: true
#https://github:com/Satyajit-Pani/nutritionapp-configuration: